# Generated by Django 5.0.6 on 2024-06-18 15:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_brand_keycap_material_keycap_profile_keycap_switch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Form_Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_keys', models.IntegerField(validators=[django.core.validators.MaxValueValidator(112)])),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.brand')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.color')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.case_material')),
                ('form_factor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.form_factor')),
            ],
        ),
        migrations.CreateModel(
            name='Plata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pin', models.CharField(choices=[('5', '5'), ('3', '3')], max_length=1)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.brand')),
                ('form_factor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.form_factor')),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.brand')),
                ('form_factor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.form_factor')),
            ],
        ),
        migrations.CreateModel(
            name='Stabilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Completed_Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keycap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.keycap')),
                ('switch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.switch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.plata')),
                ('plate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.plate')),
                ('stabilizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.stabilizer')),
            ],
        ),
    ]
