# Generated by Django 5.0.6 on 2024-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_case_material_form_factor_case_plata_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='form_factor',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='keycap',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='plata',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='plate',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='stabilizer',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='switch',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
