# Generated by Django 5.0.6 on 2024-06-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_case_url_form_factor_url_keycap_url_plata_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='image',
            field=models.ImageField(default=1, upload_to='app/switches/%Y/%m/%d'),
        ),
    ]
