# Generated by Django 5.0.6 on 2024-06-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_switch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='image',
            field=models.ImageField(default=1, upload_to='app/cases/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='keycap',
            name='image',
            field=models.ImageField(default=1, upload_to='app/keycaps/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='plata',
            name='image',
            field=models.ImageField(default=1, upload_to='app/pcb/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='plate',
            name='image',
            field=models.ImageField(default=1, upload_to='app/plates/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='stabilizer',
            name='image',
            field=models.ImageField(default=1, upload_to='app/stabs/%Y/%m/%d'),
        ),
    ]
