# Generated by Django 5.0.6 on 2024-06-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_case_image_keycap_image_plata_image_plate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
