# Generated by Django 5.0.6 on 2024-06-20 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_keycap_price_plata_price_plate_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_keyboard',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.case'),
        ),
    ]
