# Generated by Django 5.0.6 on 2024-06-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_completed_keyboard_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_factor',
            name='url',
        ),
    ]
